### ISSUE TITLE
Install soliket on macos M1

### ISSUE THREAD

**Issue by mgerbino** [simonsobs/SOLikeT#109]
This is a compilation of instructions I followed to make SOLikeT work (and pass the tox tests) on the new macos M1.

System: Monterey 12.6.3, M1 chip, arm64

The main issue was to have tensorflow correctly installed (see [here](https://developer.apple.com/metal/tensorflow-plugin/)) and have cosmopower find it. 

1. Download latest miniconda installer (e.g., here: [Download Conda environment](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh)) and properly rename it (e.g., -> miniconda.sh) 
2. Install miniconda and tensor flow-deps
`bash ~/miniconda.sh -b -p $HOME/miniconda`
`source ~/miniconda/bin/activate`
`conda install -c apple tensorflow-deps`
3. Create your virtual env
`conda env create -n my_env -f soliket-tests.yml`
`conda activate my_env`
4. Install tensorflow-macos and metal with correct versioning (I had them work with 2.9 and 0.5)
`pip install tensorflow-macos==2.9`
`pip install tensorflow-metal==0.5.0`
5. Download cosmopower manually
`git clone https://github.com/alessiospuriomancini/cosmopower`
`cd cosmopower`
6. Open requirements.txt and change the tensorflow dep as follows:
tensorflow>2.0 -> tensorflow-macos>2.0
7. Install cosmopower manually
`pip install .`
8. Go back to soliket folder and install it
`cd path/to/your/soliket`
`pip install -e .`

The above should let you install SOLikeT. 
In order to pass tests (both with pytest and within the tox env), I needed to add camb to soliket-tests.yml in the conda requirements to be installed via conda-forge (might work also via pip, not tried). Simply, add camb before the pip requirements.

**Comment by mgerbino** [comment]
Quick update: Alessio is looking into this and will likely update the PyPI to overcome the issue above.

**Comment by itrharrison** [comment]
@mgerbino can this be closed now? We should update the installation instructions in general. I think I remember the situation changed due to Alessio's action?

**Comment by mgerbino** [comment]
@itrharrison , I asked Alessio. Last time we spoke, the issue wasn't solved and we still needed to go through the procedure above to have tensowflow installed on M1
