### ISSUE TITLE
Calibration keys in theoryforge_MFLike

### ISSUE THREAD

**Issue by ggalloni** [simonsobs/SOLikeT#168]
The keys of the calibration parameters in `TheoryForge_MFLike._get_calibrated_spectra` should be single-letter strings to match the `syslib_mflike.Calibration_alm` class. This causes the mflike tests to fail.

On my fork, I tested it with the single-letter key (lines 248 and 254) and it works fine.

**Comment by sgiardie** [comment]
That is true. There have been several updates in mflike that should be ported in soliket. I think the current version of soliket is coherent with version 0.9.0 of LAT_MFLike, while we are now at version 0.9.5 in LAT_MFLike

**Comment by itrharrison** [comment]
@sgiardie how big are the changes? Will be able to do them as a small job or will it be a bit of iteration? Otherwise we should pin the required version of `syslib`.

**Comment by sgiardie** [comment]
Yes I think we can correct the bugs quickly. I can take care of that if you prefer

**Comment by itrharrison** [comment]
Yes please! 🙏

**Comment by itrharrison** [comment]
Probably when you make the change you should also update the correct requirement for `syslib` version.

**Comment by sgiardie** [comment]
There have been also two other modifications in LAT_MFLike unrelated to bugs in mflike/syslibrary, i.e. we have removed any hard coded foreground params and pulled them in the yaml and introduced the possibility for some systematics parameters not to be sampled. Do we want to add also these modifications in soliket?
