### ISSUE TITLE
SOLikeT unable to install mflike when installing on NERSC

### ISSUE THREAD

**Issue by HarrisonWinch96** [simonsobs/SOLikeT#45]
Hi,

I'm trying to install SOLikeT on NERSC, following the directions on the readme, but when I get to the `pip install -e .` step, it fails with the following error message:

`ERROR: Command errored out with exit status 1:
   command: /global/common/cori/software/python/3.6-anaconda-5.2/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fnwdimo9/mflike_3088dc3315ff48079bb30c55e1b06eb9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fnwdimo9/mflike_3088dc3315ff48079bb30c55e1b06eb9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pj858uq6
       cwd: /tmp/pip-install-fnwdimo9/mflike_3088dc3315ff48079bb30c55e1b06eb9/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fnwdimo9/mflike_3088dc3315ff48079bb30c55e1b06eb9/setup.py", line 6, in <module>
      readme = readme_file.read()
    File "/global/common/cori/software/python/3.6-anaconda-5.2/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2057: ordinal not in range(128)
  ----------------------------------------
WARNING: Discarding git+https://github.com/simonsobs/lat_mflike. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Then, at the end of the output, it says:
`ERROR: Could not find a version that satisfies the requirement mflike (unavailable) (from soliket) (from versions: none)
ERROR: No matching distribution found for mflike (unavailable)`

It seems like SOLikeT is unable to find and install the necessary mflike module, which is supposed to be installed automatically. Do you have any suggestions for how to fix this problem?

Thank you so much,
Harrison Winch

**Comment by mgerbino** [comment]
Ciao Harrison, which version of pip are you using? The easiest way I can replicate this issue is by using an old pip version (pip 9.0.1). If I upgrade to a more recent version (e.g., pip 21), I can locate and clone all required packages, including mflike. Let me know if the upgrade of pip works.

**Comment by mgerbino** [comment]
Issue solved (pip must be up-to-date, see message above). Closing.
