### ISSUE TITLE
Tests fail on new camb version

### ISSUE THREAD

**Issue by itrharrison** [simonsobs/SOLikeT#97]
Two tests against precomputed likelihood values now fail see [here,](https://github.com/simonsobs/SOLikeT/actions/runs/4067655125/jobs/7422353830#step:5:395) I'm pretty sure due to the bump in camb version to v1.4.

e.g.
```
FAILED test_clusters.py::test_clusters_loglike - assert array([False])
 +  where array([False]) = (array([-854.8981993]), -855.0)
```

I can just update the test against the new precomputed likelihood values, or change the tolerance on the `isclose`.

**Comment by itrharrison** [comment]
I can confirm that putting `camb<1.4` in the requirements.txt is another option to make the tests pass. @cmbant are you concerned about the likelihood values changing by 0.01%?

**Comment by cmbant** [comment]
Looks like a small change, similar to other likelihood test tweaks
